---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Check cached image status
  command: "machinectl image-status {{ nspawn_container_base_name }}"
  register: cache_check
  changed_when: false
  failed_when: false

- name: Set cache refresh fact
  set_fact:
    nspawn_image_cache_refresh: true
  when:
    - cache_check.rc != 0

- name: Set nspawn cache path fact
  set_fact:
    cache_index_item: "{{ nspawn_cache_map.distro }};{{ nspawn_cache_map.release }};{{ nspawn_cache_map.arch }};{{ nspawn_cache_default_variant }};"
    cache_time: "{{ ansible_date_time.epoch }}"
  when:
    - nspawn_image_cache_refresh | bool

- name: Fetch nspawn image-index
  shell: >
    aria2c
    --max-connection-per-server=4
    --allow-overwrite=true
    --dir=/tmp
    --out=index-system
    --check-certificate={{ (nspawn_hosts_validate_certs | bool) | lower }}
    {% for server in nspawn_image_cache_server_mirrors %}{{ server }}/meta/1.0/index-system {% endfor %}
  args:
    warn: no
  when:
    - nspawn_image_cache_refresh | bool
  tags:
    - skip_ansible_lint

- name: Retrieve the index
  slurp:
    src: "/tmp/index-system"
  changed_when: false
  register: image_index
  when:
    - nspawn_image_cache_refresh | bool

# Example index lines:
# ubuntu;xenial;amd64;default;20180123_08:05;/images/ubuntu/xenial/amd64/default/20180123_08:05/
# As there may be multiple images, and they use a timestamp, we can sort
# the resulting list in reverse order and use the first item in the list
# as it will be the latest available.
- name: Set image index fact
  set_fact:
    nspawn_images: >
      {%- set images = [] %}
      {%- for image in (image_index.content | b64decode).splitlines() %}
      {%- if image | match("^" + cache_index_item) %}
      {%- set _ = images.append(image) %}
      {%- endif %}
      {%- endfor %}
      {{- images | sort(reverse=True) -}}
  when:
    - nspawn_image_cache_refresh | bool

# We only want to download a single image, rather than downloading
# each of them in turn and they overwrite each other as they all
# download to the same file name and path.
- name: Pre-stage the nspawn image on the system
  shell: >
    aria2c
    --max-connection-per-server=4
    --allow-overwrite=true
    --dir=/tmp
    --out=rootfs.tar.xz
    --check-certificate={{ (nspawn_hosts_validate_certs | bool) | lower }}
    {% for server in nspawn_image_cache_server_mirrors %}{{ server }}{{ nspawn_images[0].split(';')[-1] }}rootfs.tar.xz {% endfor %}
    > /var/log/aria2c-image-prestage.log 2>&1
  args:
    warn: no
  register: prestage_image
  async: 300
  poll: 0
  when:
    - nspawn_image_cache_refresh | bool
  tags:
    - skip_ansible_lint
